name: update_history
on:
  schedule:
    - cron: '30 */1 * * *'
  repository_dispatch:
    types: [update_history]
  push:
    branches: [main]
    paths: 
      - '.github/workflows/update_history.yml'
      - 'main.py'
jobs:
  update_history:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set time
        shell: bash
        run: |
          sudo timedatectl set-timezone 'Asia/Shanghai'
      - name: Set up Python
        uses: actions/setup-python@v4 
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests

      - name: 额外工作qwq
        run: |
          curl https://rgp.zkitefly.repl.co/favicon.ico -O
          curl https://gp.zkitefly.repl.co/favicon.ico -O
        
      - name: Fetch assetIndex changes
        id: fetch_changes
        shell: bash
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          python3 main.py
          git add -A
          if git diff-index --quiet HEAD; then
            # No changes
            echo 'changed=false' >> $GITHUB_OUTPUT
          else
            # Changes detected
            echo 'changed=true' >> $GITHUB_OUTPUT
            git commit -m "Update assetIndex history （`date '+%Y-%m-%d %H:%M:%S'`）

          GitHub Action: https://github.com/${{ github.repository }}/actions/runs/$GITHUB_RUN_ID
            "
          fi
      - name: Push changes
        if: steps.fetch_changes.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
